# 1. SERVER & APP CONFIG
server.port=8813
spring.application.name=order-service

# Cho phép ghi đè Bean để tránh xung đột giữa Security, Redis và Eureka
spring.main.allow-bean-definition-overriding=true

# 2. EUREKA CLIENT CONFIG 
# spring.cloud.service-registry.auto-registration.enabled=true
eureka.instance.prefer-ip-address=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# 3. DATABASE CONFIG (SQL SERVER)
spring.datasource.url=jdbc:sqlserver://TRAMANH:1433;databaseName=orders;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Test123@
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 4. JPA & HIBERNATE CONFIG
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect
# spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# 5. REDIS & SESSION CONFIG
spring.session.store-type=redis
spring.redis.host=localhost
spring.redis.port=6379
spring.session.redis.namespace=session

# Đảm bảo Redis không chặn quá trình khởi động của các thành phần khác
spring.session.redis.initializer.order=100
eureka.client.registry-fetch-interval-seconds=5
eureka.client.initial-instance-info-replication-interval-seconds=5
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30